[package]
name = "local-gateway"
version = "0.1.0"
edition = "2021"
description = "the local backend for grafbase developer tools"
license = "Apache-2.0"
homepage = "https://grafbase.com"
keywords = ["grafbase"]
readme = "README.md"
repository = "https://github.com/grafbase/grafbase"
# TODO: populate categories
# categories = []

[dependencies]
common = { path = "../common", version = "0.1.0" }
dev-server = { path = "../dev-server", version = "0.1.0" }
exitcode = "1"
thiserror = "1"
