[package]
name = "panic-hook"
version = "0.1.0"
edition = "2021"
description = "A nicer panic. Modified version of human_panic"
license = "Apache-2.0"
homepage = "https://grafbase.com"
keywords = ["panic"]
readme = "README.md"
repository = "https://github.com/grafbase/grafbase"
# TODO: populate categories
# categories = []

[dependencies]
backtrace = "0.3"
exitcode = "1.1"
indoc = "1"
os_type = "2"
serde = "1"
serde_derive = "1"
toml = "0.5"
uuid = { version = "1", features = ["v4"] }
