[package]
name = "colorize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
hex-literal = "0.3.4"
once_cell = "1.12"
